# Generated by Django 5.0.1 on 2024-01-31 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
